// Seed/fallback data for when Supabase tables are not yet created
import type { Order, Product, CompanyProfile, PaymentSettings } from '@/types';

export const SEED_ORDERS: Order[] = [
  {
    id: 'seed-1',
    full_name: 'Ahmad Razif Ismail',
    job_title: 'Chief Executive Officer',
    company_name: 'Nexus Ventures Sdn Bhd',
    phone: '+60123456789',
    email: 'ahmad@nexusventures.my',
    website: 'https://nexusventures.my',
    linkedin: 'https://linkedin.com/in/ahmadrazif',
    whatsapp: '+60123456789',
    card_color: 'black',
    order_number: 'TIMC-2024-001',
    purchase_date: '2024-01-15',
    quantity_ordered: 10,
    status: 'completed',
    created_at: new Date(Date.now() - 5*24*3600*1000).toISOString(),
    updated_at: new Date(Date.now() - 2*24*3600*1000).toISOString(),
  },
  {
    id: 'seed-2',
    full_name: 'Priya Krishnamurthy',
    job_title: 'Head of Marketing',
    company_name: 'DigitalEdge Asia',
    phone: '+60198765432',
    email: 'priya@digitaledge.asia',
    instagram: 'https://instagram.com/priyak',
    linkedin: 'https://linkedin.com/in/priyak',
    whatsapp: '+60198765432',
    card_color: 'turquoise',
    order_number: 'TIMC-2024-002',
    purchase_date: '2024-01-18',
    quantity_ordered: 5,
    status: 'shipped',
    created_at: new Date(Date.now() - 3*24*3600*1000).toISOString(),
    updated_at: new Date(Date.now() - 1*24*3600*1000).toISOString(),
  },
  {
    id: 'seed-3',
    full_name: 'Marcus Tan Wei Liang',
    job_title: 'Senior Sales Manager',
    company_name: 'Prestige Auto Group',
    phone: '+60112233445',
    email: 'marcus@prestigeauto.my',
    website: 'https://prestigeauto.my',
    facebook: 'https://facebook.com/marcustan',
    whatsapp: '+60112233445',
    card_color: 'blue',
    order_number: 'TIMC-2024-003',
    purchase_date: '2024-01-20',
    quantity_ordered: 20,
    additional_notes: 'Sila letak logo syarikat kat belakang kad',
    status: 'in_production',
    created_at: new Date(Date.now() - 2*24*3600*1000).toISOString(),
    updated_at: new Date(Date.now() - 12*3600*1000).toISOString(),
  },
  {
    id: 'seed-4',
    full_name: 'Nur Farah Liyana',
    job_title: 'Founder & Creative Director',
    company_name: 'Studio Farah',
    phone: '+60167890123',
    email: 'farah@studiofar.ah',
    instagram: 'https://instagram.com/studiofar.ah',
    website: 'https://studiofar.ah',
    whatsapp: '+60167890123',
    card_color: 'pink',
    order_number: 'TIMC-2024-004',
    purchase_date: '2024-01-22',
    quantity_ordered: 3,
    status: 'pending_verification',
    created_at: new Date(Date.now() - 1*24*3600*1000).toISOString(),
    updated_at: new Date(Date.now() - 1*24*3600*1000).toISOString(),
  },
  {
    id: 'seed-5',
    full_name: 'Daniel Ooi Chee Keong',
    job_title: 'Investment Analyst',
    company_name: 'Meridian Capital Partners',
    phone: '+60134567890',
    email: 'daniel@meridiancap.com',
    linkedin: 'https://linkedin.com/in/danielooi',
    whatsapp: '+60134567890',
    card_color: 'white',
    order_number: 'TIMC-2024-005',
    purchase_date: '2024-01-24',
    quantity_ordered: 15,
    status: 'new',
    created_at: new Date(Date.now() - 2*3600*1000).toISOString(),
    updated_at: new Date(Date.now() - 2*3600*1000).toISOString(),
  },
  {
    id: 'seed-6',
    full_name: 'Siti Norehan Malik',
    job_title: 'HR Manager',
    company_name: 'TalentBridge Malaysia',
    phone: '+60145678901',
    email: 'norehan@talentbridge.my',
    whatsapp: '+60145678901',
    card_color: 'green',
    order_number: 'TIMC-2024-006',
    purchase_date: '2024-01-25',
    quantity_ordered: 8,
    status: 'new',
    created_at: new Date(Date.now() - 30*60*1000).toISOString(),
    updated_at: new Date(Date.now() - 30*60*1000).toISOString(),
  },
];

export const SEED_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'NFC Business Card — Standard',
    description: 'Kad NFC PVC premium dengan teknologi tap-to-share. Serasi dengan semua telefon NFC.',
    sku: 'TIMC-STD-001',
    price: 45.00,
    original_price: 60.00,
    currency: 'MYR',
    image_url: '',
    images: [],
    colors: ['black','white','blue','turquoise','pink','red'],
    in_stock: true,
    stock_count: 999,
    is_featured: true,
    sort_order: 1,
    tags: ['nfc','standard','best-seller'],
    specifications: { 'Material': 'PVC Premium', 'Thickness': '0.76mm', 'NFC Chip': 'NTAG213', 'Compatibility': 'iOS & Android' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-2',
    name: 'NFC Business Card — Metal',
    description: 'Kad NFC metal brushed aluminium dengan laser engraving. Rasa premium yang luar biasa.',
    sku: 'TIMC-MTL-001',
    price: 89.00,
    original_price: 120.00,
    currency: 'MYR',
    image_url: '',
    images: [],
    colors: ['black','silver','gold'],
    in_stock: true,
    stock_count: 50,
    is_featured: true,
    sort_order: 2,
    tags: ['nfc','metal','premium'],
    specifications: { 'Material': 'Aluminum Alloy', 'Thickness': '0.8mm', 'NFC Chip': 'NTAG216', 'Finish': 'Brushed' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-3',
    name: 'NFC Bundle — Pack 5',
    description: 'Pack 5 kad NFC standard. Sesuai untuk team dan jabatan.',
    sku: 'TIMC-BDL-005',
    price: 200.00,
    original_price: 250.00,
    currency: 'MYR',
    image_url: '',
    images: [],
    colors: ['black','white','blue'],
    in_stock: true,
    stock_count: 100,
    is_featured: false,
    sort_order: 3,
    tags: ['nfc','bundle','team'],
    specifications: { 'Quantity': '5 cards', 'Type': 'Standard PVC', 'Saving': 'Save RM50' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const SEED_COMPANY: CompanyProfile = {
  name: 'ThisIsMyCard',
  tagline: 'Premium NFC Digital Business Cards',
  description: 'Kad NFC premium yang berkualiti tinggi untuk profesional moden. Kongsi profil digital anda dengan satu ketukan.',
  logo_url: '',
  hero_image_url: '',
  email: 'hello@thisismycard.io',
  phone: '+60123456789',
  whatsapp: '+60123456789',
  address: 'Kuala Lumpur, Malaysia',
  website: 'https://thisismycard.io',
  instagram: 'https://instagram.com/thisismycard',
  facebook: 'https://facebook.com/thisismycard',
  linkedin: '',
  tiktok: '',
  youtube: '',
  twitter: '',
  shopee: '',
  lazada: '',
  business_hours: 'Isnin–Jumaat 9pagi–6petang',
};

export const SEED_PAYMENTS: PaymentSettings = {
  billplz_enabled: false,
  billplz_api_key: '',
  billplz_collection_id: '',
  billplz_x_signature: '',
  billplz_sandbox: true,
  stripe_enabled: false,
  stripe_publishable_key: '',
  stripe_secret_key: '',
  stripe_webhook_secret: '',
  stripe_sandbox: true,
  bank_transfer_enabled: true,
  bank_name: 'Maybank',
  bank_account_name: 'ThisIsMyCard Sdn Bhd',
  bank_account_number: '',
  bank_swift_code: 'MBBEMYKL',
  bank_instructions: 'Sila transfer dan hantar resit ke WhatsApp kami untuk proses segera.',
  currency: 'MYR',
  tax_enabled: false,
  tax_rate: 0,
};
